name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build Gradle
        run: ./gradlew shadowJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          path: build/libs/
        
